baseURL = "https://www.presslabs.com/docs/code/gitfs"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses = true
theme = "hugo-docs-theme"
languageCode = "en-us"
title = "Gitfs DOCS"

[markup]
  defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
  unsafe = true

[params]
  related = true
  logo_text = "CODE"
  versions = false

[params.algolia]
  appId = "0TS6NFHDBC"
  apiKey = "b2efcfd6516eed7a2f19269f9cb13acb"
  indexName = "Gitfs Docs"
  vars = ["title", "description", "content", "date", "lastmod", "permalink", "text", "lvl0", "lvl1", "url"]

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[related]
  threshold = 80
  includeNewer = true
  toLower = false
